# Use official Node.js LTS image
FROM node:22

# Set working directory inside container
WORKDIR /usr/src/app/frontend

# Copy package.json and package-lock.json
COPY package*.json ./

# Install app dependencies
RUN npm install 

# Copy rest of the application code
COPY . .

# Build the application for production
RUN npm run build

# Expose port 
EXPOSE 3000

# Run the production preview server
CMD ["npm", "run", "preview"]

