# Use official Node.js LTS image
FROM node:22

# Set working directory inside container
WORKDIR /usr/src/app/frontend

# Copy package.json and package-lock.json
COPY package*.json ./

# Install app dependencies
RUN npm install 

# Copy rest of the application code
COPY . .

# Expose port 
EXPOSE 3000

# Build the application
# RUN npm run build

# Run the application
CMD ["npm", "run", "dev"]

