# Use official Node.js LTS image
FROM node:22

# Set working directory inside container
WORKDIR /usr/src/app/

# Copy the application code
COPY . .

# BUILD FRONTEND
WORKDIR /usr/src/app/frontend

# Install packages
RUN npm install
RUN npm run build

# Expose port (change if your app uses a different port)
EXPOSE 3000

# Run the application
CMD ["npm", "run", "dist"]

