services:
  keycloak:
    container_name: synapse_auth
    image: quay.io/keycloak/keycloak:26.2.5
    ports:
        - '4000:8080'
    environment:
        KC_BOOTSTRAP_ADMIN_USERNAME: admin
        KC_BOOTSTRAP_ADMIN_PASSWORD: admin
    command: start-dev
  postgres:
      image: postgres:15
      container_name: synapse_postgres_db
      restart: unless-stopped
      environment:
        POSTGRES_USER: myuser
        POSTGRES_PASSWORD: mypassword
        POSTGRES_DB: synapse_db
      ports:
        - "4001:5432"
      volumes:
        - postgres_data:/var/lib/postgresql/data

volumes:
  postgres_data:
