# Use official Node.js LTS image
FROM node:22

# ENV VARIABLES
# Backend for seeding
ARG DATABASE_URL
ARG NODE_ENV

# Set working directory inside container
WORKDIR /usr/src/app/

# Copy the application code
COPY . .

# BUILD BACKEND
WORKDIR /usr/src/app/backend
RUN npm install
RUN npm run build-dist

# Expose port (change if your app uses a different port)
EXPOSE 8080

# Run the application
CMD ["npm", "run", "dist"]

