# Use official Node.js LTS image
FROM node:18

# Set working directory inside container
WORKDIR /usr/src/app/backend

# Copy package.json and package-lock.json
COPY package*.json ./

# Install app dependencies
RUN npm install 

# Copy rest of the application code
COPY . .

# Expose port (change if your app uses a different port)
EXPOSE 8080

# Build the application
RUN npm run build

# Run the application
CMD ["npm", "run", "dist"]

