export const DEBUG = {
	DEBUG: 'DEBUG:HELLO',
};

export const NOTIFICATION = {
	NOTIFICATION: 'NOTIFICATION:NEW-MESSAGE',
};

export const TASK = {
	MAIN_TABLE: 'TASK:REFRESH-PAGE',
	COMMENTS_SECTION: 'TASK:REFRESH-COMMENTS',
	TASK_ARCHIVED: 'TASK:ARCHIVED',
};

export const PAYLOAD_ACTIONS = {
	TASK_VIEW: 'TASK:VIEW',
	TASK_ARCHIVED: 'TASK:ARCHIVED',
};
