FROM nginx:latest

# Copy custom nginx configuration file
COPY nginx.conf /etc/nginx/nginx.conf

# Copy your website files
COPY ./html /usr/share/nginx/html

# COPY SSL Certification
COPY ./certs /etc/nginx/ssl

EXPOSE 80

CMD ["nginx", "-g", "daemon off;"]
